### ISSUE TITLE
trackedFunction return types seem wonky.

### ISSUE THREAD

**Issue by RobbieTheWagner** [universal-ember/reactiveweb#103]
It seems to think it returns `{}` and does not factor in `isLoading` etc, so glint cannot find those `State` props.

**Comment by NullVoxPopuli** [comment]
Any chance you can repro in https://tsplay.dev/ ?

**Comment by NullVoxPopuli** [comment]
I came up with this, and it seems like it works as expected:

https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzjKBDAxgawKYBMBiArgHbozATEA0yAnmNnAMoyoyMC+cAZlBCHADkUbBnIA3bAHdsAIwD03EmQrFBAbgBQoSLERxsADwZkAKvWwB5bnC69+QoyZgBaGBY2bNT6PCWlySjh8CAgACmBcAC44YkIQWWwoAEpETQBIERhCKGJkNCw8IgDVMNQAZ1pSODDUgF4APjT09NQpVGB4AAYtFqycvKRI216OZK0OLydsMwtrAB4AJWxs3PMGefcGCBsQiAaG2oA6GAgAUQBHQlQAG3WrbnmWNmx5gAU+EGBy16Ho2PiiSgtgOh3G3mMMxg9wWy1WxHumwsO2CoQaAG1BN8ADIQVC4YDEADmggAumCTucrrcYY9ZKEbqJiGCtEA

maybe you could modify it to be closer to your use case?

**Comment by NullVoxPopuli** [comment]
Gonna close -- please lemme know if there is still an issue, and we can re-open!
